# -*- coding: utf-8 -*-
"""pds_16345441_q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lfOwCkOxco5h92g41z-yWvAQn8TqSES3

DATA PREPARATION
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

# Load the data
data = pd.read_csv('raw_data.csv')
data
data.to_csv('cleaned_Data.csv', index=False)

# Generate a direct download link
from google.colab import files
files.download('cleaned_Data.csv')

"""DATA ANALYSIS"""

# Calculate the descriptive statistics
descriptive_stats = data.describe()
descriptive_stats.to_csv('descriptive_stats.csv', index=False)
descriptive_stats

# Create a correlation matrix
correlation_matrix = data.corr()
correlation_matrix.to_csv('correlation_matrix.csv', index=False)
correlation_matrix

# Plot the grip strength vs. age
plt.figure()
plt.scatter(data['Age'], data['Grip strength'])
plt.xlabel('Age')
plt.ylabel('Grip strength')
plt.title('Grip strength vs. age')
plt.savefig('grip_strength_vs_age.png')

# Plot the grip strength vs. frailty
plt.figure()
plt.scatter(data['Grip strength'], data['Frailty'])
plt.xlabel('Grip strength')
plt.ylabel('Frailty')
plt.title('Grip strength vs. frailty')
plt.savefig('grip_strength_vs_frailty.png')